  
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11

    working_directory: $CIRCLE_WORKING_DIRECTORY/root/backend
    steps:
      
      - run: npm install
      
      # run tests!
      - run: npm test
