jobs:
  test:
    working_directory: ~/SudokuProject/root/backend
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages
      - run: npm run test
orbs:
  node: 'circleci/node@2.0.0'
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
